<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE personer [
    <!ELEMENT personer (person*)>
    <!ELEMENT person (pnr, fornavn, etternavn, fodselsdato)>
    <!ELEMENT pnr (#PCDATA)>
    <!ELEMENT fornavn (#PCDATA)>
    <!ELEMENT etternavn (#PCDATA)>
    <!ELEMENT fodselsdato (#PCDATA)>
]>

<personer>
    <person>
        <pnr>1</pnr>
        <fornavn>Ola</fornavn>
        <etternavn>Nordmann</etternavn>
        <fodselsdato>1980-01-01</fodselsdato>
    </person>
    <person>
        <pnr>2</pnr>
        <fornavn>Kari</fornavn>
        <etternavn>Pettersen</etternavn>
        <fodselsdato>1993-08-23</fodselsdato>
    </person>
</personer>
