=== 186469/hvl-dat107-databaser-V2025/forelesninger/xml/forelesning01/eksempler/personer1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <!-- Elementdefinisjoner -->
   <xs:element name="personer" type="personerType" />

   <!-- Typedefinisjoner: COMPLEX -->
   <xs:complexType name="personerType">
      <xs:sequence>
         <xs:element name="person" type="personType" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="personType">
      <xs:sequence>
         <xs:element name="pnr" type="pnrType" />
         <xs:element name="fornavn" type="fornavnType" />
         <xs:element name="etternavn" type="xs:string" />
         <xs:element name="barn" type="xs:integer" minOccurs="0"/>
         <xs:element name="fodselsdato" type="xs:date" />
         <xs:element name="erStudent" type="xs:boolean" minOccurs="0"/>
      </xs:sequence>
   </xs:complexType>

   <!-- Typedefinisjoner: SIMPLE -->
   <xs:simpleType name="pnrType">
      <xs:restriction base="xs:integer">
         <xs:enumeration value="1"/>
         <xs:enumeration value="2"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="fornavnType">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Ola"/>
         <xs:enumeration value="Kari"/>
      </xs:restriction>
   </xs:simpleType>
</xs:schema>

=== 186469/hvl-dat107-databaser-V2025/forelesninger/xml/forelesning01/eksempler/personer.xml
<?xml version="1.0" encoding="UTF-8"?>

<personer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="personer1.xsd">
   <person>
      <pnr>1</pnr>
      <fornavn>Ola</fornavn>
      <etternavn>Norman</etternavn>
      <fodselsdato>1980-01-01</fodselsdato>
   </person>
   <person>
      <pnr>2</pnr>
      <fornavn>Kari</fornavn>
      <etternavn>Petersen</etternavn>
      <fodselsdato>1993-08-23</fodselsdato>
      <erStudent>true</erStudent>
   </person>
   <!--
   <person>
      <pnr>3</pnr>
      <fornavn>Per</fornavn>
      <etternavn>Hansen</etternavn>
      <fodselsdato>1975-12-31</fodselsdato>
   </person>
   -->
</personer>
