=== 186469/hvl-dat107-databaser-V2025/forelesninger/xml/forelesning01/eksempler/test-mixed.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <!-- Elementer -->
   <xs:element name="mainContent" type="mainContentType" />

   <!-- Typedefinisjoner: COMPLEX -->
   <xs:complexType name="mainContentType">
      <xs:sequence>
         <xs:element name="noMix" type="noMixContentType" minOccurs="1" maxOccurs="1" />
         <xs:element name="mixed" type="mixedContentType" minOccurs="1" maxOccurs="1" />
         <xs:element name="registered" type="xs:dateTime" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="noMixContentType">
      <xs:sequence>
         <xs:element name="bold" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="italic" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="mixedContentType" mixed="true">
      <xs:sequence>
         <xs:element name="bold" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="italic" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
</xs:schema>

=== 186469/hvl-dat107-databaser-V2025/xml/forelesninger/forelesning01/eksempler/test-mixed.xml
<?xml version="1.0" encoding="UTF-8"?>
<mainContent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="test-mixed.xsd">
   <noMix>
      Dette ligner litt på HTML språket. Der <bold>noe tekst</bold> kan være <bold>fet</bold>,
      og <italic>noe annet</italic> kan være <italic>kursiv</italic>.
   </noMix>
   <mixed>
      Dette ligner litt på HTML språket. Der <bold>noe tekst</bold> kan være <bold>fet</bold>,
      og <italic>noe annet</italic> kan være <italic>kursiv</italic>.
   </mixed>
   <registered>2020-10-01T01:13:00</registered>
</mainContent>
