=== 186469/hvl-dat107-databaser-V2025/øvinger/oving-02/oppgave1/fag.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns="http://oving.hvl.no/fag"
           targetNamespace="http://oving.hvl.no/fag"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:dat="http://oving.hvl.no/fag">

	<xs:element name="hvl" type="hvlType" />
	
	<!--  Complex Types -->
	<xs:complexType name="hvlType">
		<xs:sequence>
			<xs:element name="emner" type="emnerType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>    
	
	<xs:complexType name="emnerType">
		<xs:sequence>
			<xs:element name="emne" type="emneType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="emneType">
		<xs:sequence>
			<xs:element name="kode" type="kodeType" />
			<xs:element name="navn" type="navnType" />
			<xs:element name="poeng" type="poengType" />
			<xs:element name="semester" type="semesterType" />
		</xs:sequence>
	</xs:complexType>     
	
	<!--  SimpleType definitions -->
	<xs:simpleType name="kodeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="['DAT','MAT','ING']{3}[0-3]{1}[0-9]{2}" />
		</xs:restriction>
	</xs:simpleType>  
	
	<xs:simpleType name="navnType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"></xs:minLength>
			<xs:maxLength value="100"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="poengType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="100" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="semesterType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="6" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== 186469/hvl-dat107-databaser-V2025/xml/øvinger/oving-02/oppgave1/fag.xml
<?xml version = "1.0" encoding="utf-8"?>
<?xml-stylesheet type = "text/xsl" href = "fag2.xsl"?>
<!-- <hvl> -->
<!-- <hvl xmlns="http://oving.hvl.no/fag"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://oving.hvl.no/fag fag.xsd"> -->
<hvl xmlns="http://oving.hvl.no/fag"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://oving.hvl.no/fag fag.xsd">
   <emner>
      <emne><kode>DAT100</kode><navn>Grunnleggende Programmering</navn><poeng>10</poeng><semester>1</semester></emne>
      <emne><kode>MAT101</kode><navn>Diskret Matematikk 1</navn><poeng>10</poeng><semester>1</semester></emne>
      <emne><kode>ING100</kode><navn>Ingeniørfaglig</navn><poeng>5</poeng><semester>1</semester></emne>
      <emne><kode>DAT111</kode><navn>Introduksjon til programvareutvikling</navn><poeng>5</poeng><semester>1</semester></emne>
      <emne><kode>DAT102</kode><navn>Algoritmer og datastrukturer</navn><poeng>10</poeng><semester>2</semester></emne>
      <emne><kode>DAT107</kode><navn>Databaser</navn><poeng>10</poeng><semester>2</semester></emne>
      <emne><kode>MAT104</kode><navn>Grunnleggende matematikk for informasjonsteknologi</navn><poeng>10</poeng><semester>2</semester></emne>
      <emne><kode>MAT210</kode><navn>Videregående diskret matematikk</navn><poeng>5</poeng><semester>3</semester></emne>
      <emne><kode>MAT122</kode><navn>Statistikk for ingenilører</navn><poeng>5</poeng><semester>3</semester></emne>
      <emne><kode>DAT108</kode><navn>Programmering og webapplikasjoner</navn><poeng>10</poeng><semester>3</semester></emne>
      <emne><kode>DAT103</kode><navn>Datamaskiner og operativsystemer</navn><poeng>10</poeng><semester>3</semester></emne>
      <emne><kode>DAT109</kode><navn>Systemutvikling</navn><poeng>10</poeng><semester>4</semester></emne>
      <emne><kode>DAT110</kode><navn>Distribuerte systemer og nettverksteknologi</navn><poeng>10</poeng><semester>4</semester></emne>
      <emne><kode>DAT154</kode><navn>Programvarearkitektur og applikasjonsutvikling</navn><poeng>10</poeng><semester>4</semester></emne>
      <emne><kode>DAT152</kode><navn>Videregående webapplikasjoner</navn><poeng>10</poeng><semester>5</semester></emne>
      <emne><kode>DAT156</kode><navn>Praksis i arbeidslivet for data</navn><poeng>10</poeng><semester>5</semester></emne>
      <emne><kode>DAT158</kode><navn>Maskinlæring og videregående algoritmer</navn><poeng>10</poeng><semester>5</semester></emne>
      <emne><kode>DAT150</kode><navn>Nettverksadministrasjon, drift og sikkerhet</navn><poeng>10</poeng><semester>5</semester></emne>
      <emne><kode>DAT153</kode><navn>Mobile og distribuerte applikasjoner</navn><poeng>10</poeng><semester>6</semester></emne>
      <emne><kode>DAT155</kode><navn>3D Datagrafikk</navn><poeng>10</poeng><semester>6</semester></emne>
      <emne><kode>DAT151</kode><navn>Drift av Unix og databaser</navn><poeng>10</poeng><semester>6</semester></emne>
      <emne><kode>DAT253</kode><navn>Avansert datagrafikk</navn><poeng>10</poeng><semester>6</semester></emne>
      <emne><kode>DAT191</kode><navn>Bacheloroppgave</navn><poeng>20</poeng><semester>5</semester></emne>
      <emne><kode>ING303</kode><navn>Systemtenking og innovasjon for ingeniører</navn><poeng>10</poeng><semester>5</semester></emne>
   </emner>
</hvl>
